# Set some defaults

# Set git with defaults
git config --global core.autocrlf input
git config --global core.fileMode false
# /Set some defaults


# Connect to private repositories if any
# ...
# ...
# ...
# /Connect to private repositories if any

# You custom commands
# ...
# ...
# ...
# /You custom commands